In [ ]:
import pandas as pd
data_path = '/content/drive/MyDrive/train.csv'
df = pd.read_csv(data_path)
df.head(10)

battery_power  blue  clock_speed  ...  touch_screen  wifi  price_range
0            842     0          2.2  ...             0     1            1
1           1021     1          0.5  ...             1     0            2
2            563     1          0.5  ...             1     0            2
3            615     1          2.5  ...             0     0            2
4           1821     1          1.2  ...             1     0            1
5           1859     0          0.5  ...             0     0            1
6           1821     0          1.7  ...             0     1            3
7           1954     0          0.5  ...             1     1            0
8           1445     1          0.5  ...             0     0            0
9            509     1          0.6  ...             0     0            0

[10 rows x 21 columns]

In [ ]:
import numpy as np
Y = np.array(df['price_range'], dtype=np.float32)
print(Y.shape)
X = df.drop(['price_range'], axis=1)
X = np.array(X, dtype=np.float32) # so luong dien thoai và thuoc tinh
print(X.shape)

(2000,)
(2000, 20)


In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

In [ ]:
# bat dau train
import time
from sklearn.svm import SVC

start=time.time()
model = SVC(kernel='linear', random_state=42)
model.fit(x_train, y_train)
end=time.time()
print(end-start)
acc = round(model.score(x_train, y_train)*100, 2)
print(acc)

#danh gia tinh chinh xac cua mo hinh
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support

conf = confusion_matrix(y_test, y_pred)
print(conf)

precision, recall, f1score = precision_recall_fscore_support(y_test, y_pred, average='weighted')[:3]
print(precision, recall, f1score)

9.382476568222046
99.21
[[144   7   0   0]
 [ 12 126   8   0]
 [  0  19 117  12]
 [  0   0  11 144]]
0.8846856394379614 0.885 0.8843307497319173


In [ ]:
y_pred = model.predict(x_test)
print(y_pred[1],x_test[1]) #xuat ket qua khi biet dau vao cua 1 test
print(y_pred) # xuat tat ca cac ket qua khi co cac test dau vao

2.0 [1.182e+03 0.000e+00 5.000e-01 0.000e+00 7.000e+00 1.000e+00 8.000e+00
 5.000e-01 1.380e+02 8.000e+00 1.600e+01 2.750e+02 9.860e+02 2.563e+03
 1.900e+01 1.700e+01 1.900e+01 1.000e+00 0.000e+00 0.000e+00]
[0. 2. 1. 3. 1. 1. 2. 0. 3. 1. 0. 1. 2. 3. 3. 2. 3. 3. 1. 0. 0. 2. 1. 2.
 0. 1. 3. 2. 2. 0. 0. 0. 3. 0. 1. 1. 2. 0. 3. 0. 2. 3. 2. 0. 3. 3. 2. 1.
 3. 1. 3. 1. 0. 0. 1. 1. 1. 3. 0. 0. 1. 3. 3. 1. 0. 0. 3. 3. 1. 2. 2. 2.
 0. 1. 2. 0. 1. 3. 2. 2. 3. 2. 1. 0. 1. 3. 1. 3. 3. 0. 3. 3. 2. 1. 3. 2.
 2. 3. 1. 1. 0. 0. 1. 0. 1. 3. 2. 0. 1. 1. 0. 0. 3. 1. 3. 2. 3. 2. 0. 2.
 1. 3. 2. 1. 3. 3. 0. 2. 0. 2. 3. 0. 2. 2. 0. 3. 1. 0. 0. 2. 2. 1. 2. 2.
 0. 0. 0. 1. 1. 2. 3. 1. 1. 0. 2. 2. 0. 1. 0. 2. 2. 3. 3. 3. 1. 0. 1. 2.
 2. 3. 3. 0. 1. 0. 3. 1. 1. 2. 1. 0. 0. 0. 0. 0. 3. 2. 0. 3. 0. 0. 0. 0.
 1. 3. 3. 1. 0. 1. 1. 1. 1. 2. 2. 3. 3. 3. 1. 2. 0. 0. 0. 2. 1. 1. 3. 1.
 1. 2. 1. 1. 3. 2. 3. 0. 0. 2. 1. 3. 0. 1. 2. 0. 2. 3. 2. 0. 1. 3. 3. 0.
 1. 3. 3. 3. 0. 3. 1. 2. 3. 3. 2. 1. 0. 3. 3. 1. 3. 3. 3. 3. 3

In [ ]:
# so sanh chay voi mo hinh logistic
import time
from sklearn.linear_model import LogisticRegression
start=time.time()
model = LogisticRegression(random_state=0).fit(x_train, y_train)
end=time.time()
print(end-start)
acc = round(model.score(x_train, y_train)*100, 2)
print(acc)
y_pred = model.predict(x_test)
conf = confusion_matrix(y_test, y_pred)
print(conf)

0.10048127174377441
64.07
[[114  36   1   0]
 [ 27  73  37   9]
 [  1  30  79  38]
 [  0   3  37 115]]


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
# so sanh chay voi mo hinh knn
import  time
from sklearn.neighbors import KNeighborsClassifier
start=time.time()
model = KNeighborsClassifier(n_neighbors=3).fit(x_train, y_train)
end=time.time()
print(end-start)
acc = round(model.score(x_train, y_train)*100, 2)
print(acc)
y_pred = model.predict(x_test)
# print(x_test[1], model.predict(x_test[1][np.newaxis, ...]))
conf = confusion_matrix(y_test, y_pred)
print(conf)

0.0048580169677734375
96.07
[[143   8   0   0]
 [  6 135   5   0]
 [  0  13 125  10]
 [  0   0  10 145]]


In [ ]:
# so sanh chay voi mo hinh random forest
import time
from sklearn.ensemble import RandomForestClassifier
start=time.time()
model = RandomForestClassifier(criterion='entropy').fit(x_train, y_train)
end=time.time()
print(end-start)
acc = round(model.score(x_train, y_train)*100, 2)
print(acc)
y_pred = model.predict(x_test)
conf = confusion_matrix(y_test, y_pred)
print(conf)

0.5353724956512451
100.0
[[144   7   0   0]
 [ 12 126   8   0]
 [  0  19 117  12]
 [  0   0  11 144]]
