In [2]:
import pandas as pd # khai báo thư viện Pandas để xử lý dữ liệu
data_path = r'train.csv'  #đường dẫn đến thư mục train
df = pd.read_csv(data_path) #dữ liệu train
df.head(10) #hiển thị 10 dữ liệu đầu

battery_power  blue  clock_speed  ...  touch_screen  wifi  price_range
0            842     0          2.2  ...             0     1            1
1           1021     1          0.5  ...             1     0            2
2            563     1          0.5  ...             1     0            2
3            615     1          2.5  ...             0     0            2
4           1821     1          1.2  ...             1     0            1
5           1859     0          0.5  ...             0     0            1
6           1821     0          1.7  ...             0     1            3
7           1954     0          0.5  ...             1     1            0
8           1445     1          0.5  ...             0     0            0
9            509     1          0.6  ...             0     0            0

[10 rows x 21 columns]

In [3]:
import numpy as np
Y = np.array(df['price_range'], dtype=np.float32) # lấy dữ liệu của giá sản phẩm
print(Y.shape)
X = df.drop(['price_range'], axis=1)
X = np.array(X, dtype=np.float32) # so luong dien thoai và thuoc tinh
print(X.shape)

(2000,)
(2000, 20)


In [8]:
from sklearn.model_selection import train_test_split 

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)
# chia tập dữ liệu thành 2 phần: 70% data train,30% data test

In [9]:
# bắt đầu train
import time #Sử dụng để tính thòi gian train
from sklearn.svm import SVC #thư viện giải SVM trên Scikit-learn

start=time.time()# thời gian bắt đầu train
modelSVM = SVC(kernel='rbf', random_state=42) # lựa chọn Kernel: Radial Basic Function
modelSVM.fit(x_train, y_train)#Sử dụng model huấn luyện trên tập x_train và y_train
end=time.time() # kết thúc
print(end-start) # thời gian chạy chương trình
acc = round(modelSVM.score(x_train, y_train)*100, 2) # độ chính xác
print(acc)

y_pred = modelSVM.predict(x_test)# kết quả dự đoán giá tập test

#đánh giá tính chính xác của mô hình
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support

conf = confusion_matrix(y_test, y_pred) # ma trận nhầm lẫn
print(conf)

precision, recall, f1score = precision_recall_fscore_support(y_test, y_pred, average='weighted')[:3]
print(precision, recall, f1score)

0.035271644592285156
95.5
[[146   5   0   0]
 [  1 144   1   0]
 [  0   9 134   5]
 [  0   0   7 148]]
0.9543878210145808 0.9533333333333334 0.9533482896190848


In [ ]:
# xuất kết quả dự đoán tập test của mô hình
print(y_pred[1],x_test[1]) #xuất kết quả khi biết đầu vào của 1 test
print(y_pred) # xuất tất cả kết quả khi biết đầu vào

In [ ]:
# so sánh với mô hình hồi quy Logistic
import time
from sklearn.linear_model import LogisticRegression
start=time.time()
model = LogisticRegression(random_state=42).fit(x_train, y_train)
end=time.time()
print(end-start)
acc = round(model.score(x_train, y_train)*100, 2)
print(acc)
y_pred = model.predict(x_test)
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support
conf = confusion_matrix(y_test, y_pred)
print(conf)
# độ chính xác, bao phủ, harmonic mean của mô hình
precision, recall, f1score = precision_recall_fscore_support(y_test, y_pred, average='weighted')[:3]
print(precision, recall, f1score)


In [ ]:
# so sánh với mô hình KNN
import  time
from sklearn.neighbors import KNeighborsClassifier
start=time.time()
model = KNeighborsClassifier(n_neighbors=3).fit(x_train, y_train) # chọn 3 điểm data gần nhất
end=time.time()
print(end-start)
acc = round(model.score(x_train, y_train)*100, 2)
print(acc)
y_pred = model.predict(x_test)
# print(x_test[1], model.predict(x_test[1][np.newaxis, ...]))
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support
conf = confusion_matrix(y_test, y_pred)
print(conf)

precision, recall, f1score = precision_recall_fscore_support(y_test, y_pred, average='weighted')[:3]
print(precision, recall, f1score)

In [ ]:
# so sánh với mô hình DecisionTree
import time
from sklearn.tree import DecisionTreeClassifier
start=time.time()
model=DecisionTreeClassifier().fit(x_train,y_train)
end=time.time()
print(end-start)
acc = round(model.score(x_train, y_train)*100, 2)
print(acc)
y_pred = model.predict(x_test)
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support
conf = confusion_matrix(y_test, y_pred)
print(conf)

precision, recall, f1score = precision_recall_fscore_support(y_test, y_pred, average='weighted')[:3]
print(precision, recall, f1score)

In [ ]:
#du doan gia cac dien thoai trong tap test.csv bang model SVM o tren
import pandas as pd # khai báo thư viện Pandas để xử lý dữ liệu
data_path2 = r'test.csv'  #đường dẫn đến thư mục test
x_dudoan = pd.read_csv(data_path2) #dữ liệu test
x_dudoan = np.array(X, dtype=np.float32) 
y_dudoan = modelSVM.predict(x_dudoan)
print(y_dudoan)